### PR TITLE
Clean up temp files on the way out

### PR DESCRIPTION
**Pull request by gabek**
Looking to fix https://github.com/bogem/id3v2/issues/9.

### CODE REVIEW

**Comment by gabek** [comment]
As a golang newbie, I don't know if this is the right approach or not.  Is checking for the existence, and closing the file handler of the tmp file needed?

**Comment by mro** [comment]
not sure about close (think it's superficial), I also wouldn't check existence, but rather just try to remove. Non-existence may point to rights or space issues, but that's a thing for the open to care about.

**Comment by gabek** [comment]
Great!  Just simplified it down to only the removal.

**Comment by bogem** [comment]
Can you please accommodate the changes if `tag.go` file in one commit?

**Comment by gabek** [comment]
No problem.  Done.

**Comment by bogem** [comment]
Good. Thank you, @gabek!

**Pull request merged**
